---
title: "Prepare various bits of data"
output: html_notebook
---


Prepares extra sectors....

```{r}

library(dplyr)

```



```{r}
library(dplyr)
if (Sys.info()["nodename"] == "PCACL-9RVSQ74") {
  datad="C:\\Users\\rmartin7\\OneDrive - WBG\\projects\\PRINZGlobal\\imperial_college_visualization\\01_data"
  localbig="C:\\Users\\rmartin7\\OneDrive - Imperial College London\\inglobe"
  ifcone="C:\\Users\\rmartin7\\OneDrive - WBG\\projects\\PRINZGlobal\\KEVCexplorer"
}




source("istraxfunctions.R")
dropbox_root <- get_dropbox_path()



```


# cpc data

```{r}
cpcfile=paste0(dropbox_root,"\\apps\\iseapp\\background_data\\cpcs.fst")
if (!file.exists(cpcfile)) {
  library(bigrquery)
  library(DBI)
  
  # Set your project ID
  project_id <- "patbis"
  
  # Option 1: Direct table download
  # Specify dataset and table name
  dataset <- "fromPATSTAT2021"
  table <- "tls225_docdb_fam_cpc"
  
  # Download the entire table
  cpcs <- bq_table_download(
    bq_table(project_id, dataset, table)
  )
  
  
  cpcs=cpcs %>% select(docdb_family_id,cpc_class_symbol)
  cpcs=cpcs %>% arrange(docdb_family_id)
  library(fst2)
  write_fst(cpcs,cpcfile,compress=100)
}




```


  
```{r}

library(arrow)
cpcs=read_fst(cpcfile)


#test=cpcs %>% summarize(n_distinct(docdb_family_id))

cpcs=cpcs %>% arrange(docdb_family_id)

head(cpcs)
library(stringr)

## get sections...
sectionmap1=cpcs %>% mutate(section=substr(cpc_class_symbol,1,1)) %>%
  select(section,docdb_family_id) %>% 
  distinct()

sectionmap1 %>% distinct(section) %>% nrow()
sectionmap1 %>% distinct(section) %>% pull(section)  %>% cat()


sectionmap2=cpcs %>% mutate(section=substr(cpc_class_symbol,1,3)) %>%
  select(section,docdb_family_id) %>% 
  distinct()

sectionmap2 %>% distinct(section) %>% nrow()
sectionmap2 %>% distinct(section) %>% pull(section)  %>% cat()



cpcs=cpcs %>% gsub(" ", "", cpc_class_symbol)



library(data.table)
library(stringi)

setDT(cpcs)
cpcs[, cpc_class_symbol := stri_replace_all_fixed(cpc_class_symbol, " ", "")]


```





# Hard to abate sectors


```{r}
library(readxl)
tech_df <- read_excel("hard_to_abate.xlsx") %>% 
  rename(detail=technology,technology=sector) %>% 
  mutate(technology=paste0(technology," Decarbonisation"))


tech_df_expanded <- tech_df %>%
  separate_rows(CPC, sep = ";")%>%
  mutate(cpc_class_symbol = trimws(CPC))

setDT(tech_df_expanded)
tech_df_expanded[, cpc_class_symbol := stri_replace_all_fixed(cpc_class_symbol, " ", "")]


tech_df %>% 
  distinct(technology) %>% 
  pull(technology) %>% 
  paste0('"', ., '"') %>%
  paste(collapse = ", ") %>% cat()



tech_classes=cpcs %>% inner_join(tech_df_expanded %>% select(technology,cpc_class_symbol)) 

all=tech_classes %>% distinct(docdb_family_id) %>% mutate(technology="Any Hard to Abate technology")
tech_classes=tech_classes %>% bind_rows(all)
tech_classes=tech_classes %>% select(docdb_family_id,technology)



```



```{r}


techmap <- read_parquet("techmap.parquet")
techs=techmap %>% distinct(technology)

if(!"Aviation Decarbonisation" %in% techs){
  techmap=techmap %>% bind_rows(tech_classes)
  
  write_parquet(techmap,"techmap.parquet")
}


```




# AI

```{r}
library(readxl)
tech_df <- read_excel("New_Sector_mapping.xlsx",sheet="AI") %>% 
  rename(CPC=`CPC/IPC Codes`) %>% 
  rename(technology=`Sub-Technology`) %>% filter(!is.na(technology))
  
  

tech_df_expanded <- tech_df %>%
  separate_rows(CPC, sep = ",")%>%
  mutate(cpc_class_symbol = trimws(CPC))

setDT(tech_df_expanded)
tech_df_expanded[, cpc_class_symbol := stri_replace_all_fixed(cpc_class_symbol, " ", "")]


tech_df %>% 
  distinct(technology) %>% 
  pull(technology) %>% 
  paste0('"', ., '"') %>%
  paste(collapse = ", ") %>% cat()



tech_classes=cpcs %>% inner_join(tech_df_expanded %>% select(technology,cpc_class_symbol)) 

#all=tech_classes %>% distinct(docdb_family_id) %>% mutate(technology="Any Hard to Abate technology")
#tech_classes=tech_classes %>% bind_rows(all)
tech_classes=tech_classes %>% select(docdb_family_id,technology)



```



```{r}

library(fst)
techmap <- read_parquet("techmap.parquet")
techs=techmap %>% distinct(technology)

if(!"Machine Learning" %in% techs){
  techmap=techmap %>% bind_rows(tech_classes)
  techmap=techmap %>% distinct()
  #write_parquet(techmap,"techmap.parquet")
  write_fst(techmap,"techmap.fst")
}



```


# CPC sections

```{r}

cpc <- c(
  A = "Human Necessities",
  B = "Performing Operations; Transporting",
  C = "Chemistry; Metallurgy",
  D = "Textiles; Paper",
  E = "Fixed Constructions",
  F = "Mechanical Engineering; Lighting; Heating; Weapons; Blasting",
  G = "Physics",
  H = "Electricity",
  Y = "General tagging of new or cross-sectional technology"
)

cpc_df <- data.frame(
  section = names(cpc),
  heading = unname(cpc)
)

cpc_classes <- c(
  A01 = "Agriculture; Forestry; Animal husbandry; Hunting; Trapping; Fishing",
  A21 = "Baking; Edible doughs",
  A22 = "Butchering; Meat treatment; Processing poultry or fish",
  A23 = "Foods or foodstuffs; Treatment thereof",
  A24 = "Tobacco; Cigars; Cigarettes; Smokers' requisites",
  A41 = "Wearing apparel",
  A42 = "Headwear",
  A43 = "Footwear",
  A44 = "Haberdashery; Jewellery",
  A45 = "Hand or travelling articles",
  A46 = "Brushware",
  A47 = "Furniture; Domestic articles or appliances; Coffee mills; Spice mills; Suction cleaners",
  A61 = "Medical or veterinary science; Hygiene",
  A62 = "Life-saving; Fire-fighting",
  A63 = "Sports; Games; Amusements",
  A99 = "Subject matter not otherwise provided for in this section",
  
  B01 = "Physical or chemical processes or apparatus in general",
  B02 = "Crushing, pulverising, or disintegrating; Preparatory treatment of grain for milling",
  B03 = "Separation of solid materials using liquids or using pneumatic tables",
  B04 = "Centrifugal apparatus or machines for carrying-out physical or chemical processes",
  B05 = "Spraying or atomising in general; Applying fluent materials to surfaces",
  B06 = "Generating or transmitting mechanical vibrations in general",
  B07 = "Separating solids from solids; Sorting",
  B08 = "Cleaning",
  B09 = "Disposal of solid waste; Reclamation of contaminated soil",
  B21 = "Mechanical metal-working without essentially removing material; Punching metal",
  B22 = "Casting; Powder metallurgy",
  B23 = "Machine tools; Metal-working not otherwise provided for",
  B24 = "Grinding; Polishing",
  B25 = "Hand tools; Portable power-driven tools; Manipulators",
  B26 = "Hand cutting tools; Cutting; Severing",
  B27 = "Working or preserving wood or similar material; Nailing or stapling machines",
  B28 = "Working cement, clay, or stone",
  B29 = "Working of plastics; Working of substances in a plastic state in general",
  B30 = "Presses",
  B31 = "Making articles of paper, cardboard or material worked in a manner analogous to paper",
  B32 = "Layered products",
  B33 = "Additive manufacturing technology",
  B41 = "Printing; Lining machines; Typewriters; Stamps",
  B42 = "Bookbinding; Albums; Files; Special printed matter",
  B43 = "Writing or drawing implements; Bureau accessories",
  B44 = "Decorative arts",
  B60 = "Vehicles in general",
  B61 = "Railways",
  B62 = "Land vehicles for travelling otherwise than on rails",
  B63 = "Ships or other waterborne vessels; Related equipment",
  B64 = "Aircraft; Aviation; Cosmonautics",
  B65 = "Conveying; Packing; Storing; Handling thin or filamentary material",
  B66 = "Hoisting; Lifting; Hauling; Pushing; Positioning",
  B67 = "Opening, closing or cleaning bottles, jars or similar containers; Liquid handling",
  B68 = "Saddlery; Upholstery",
  B81 = "Microstructural technology",
  B82 = "Nanotechnology",
  
  C01 = "Inorganic chemistry",
  C02 = "Treatment of water, waste water, sewage, or sludge",
  C03 = "Glass; Mineral or slag wool",
  C04 = "Cements; Concrete; Artificial stone; Ceramics; Refractories",
  C05 = "Fertilisers; Manufacture thereof",
  C06 = "Explosives; Matches",
  C07 = "Organic chemistry",
  C08 = "Organic macromolecular compounds; Their preparation or chemical working-up; Compositions",
  C09 = "Dyes; Paints; Polishes; Natural resins; Adhesives; Compositions; Miscellaneous applications",
  C10 = "Petroleum, gas or coke industries; Technical gases containing carbon monoxide",
  C11 = "Animal or vegetable oils, fats, fatty substances or waxes; Fatty acids; Detergents; Candles",
  C12 = "Biochemistry; Beer; Spirits; Wine; Vinegar; Microbiology; Enzymology; Mutation or genetic engineering",
  C13 = "Sugar industry",
  C14 = "Skins; Hides; Pelts; Leather",
  C21 = "Metallurgy of iron",
  C22 = "Metallurgy; Ferrous or non-ferrous alloys; Treatment of alloys or non-ferrous metals",
  C23 = "Coating metallic material; Coating material with metallic material; Surface treatment",
  C25 = "Electrolytic or electrophoretic processes; Apparatus therefor",
  C30 = "Crystal growth",
  C40 = "Combinatorial technology",
  C99 = "Subject matter not otherwise provided for in this section",
  
  D01 = "Natural or man-made threads or fibres; Spinning",
  D02 = "Yarns; Mechanical finishing of yarns or ropes; Warping or beaming",
  D03 = "Weaving",
  D04 = "Braiding; Lace-making; Knitting; Trimmings; Non-woven fabrics",
  D05 = "Sewing; Embroidering; Tufting",
  D06 = "Treatment of textiles or the like; Laundering; Flexible materials not otherwise provided for",
  D07 = "Ropes; Cables other than electric",
  D10 = "Indexing scheme associated with subclasses of section D, relating to textiles",
  D21 = "Paper-making; Production of cellulose",
  
  E01 = "Construction of roads, railways, or bridges",
  E02 = "Hydraulic engineering; Foundations; Soil shifting",
  E03 = "Water supply; Sewerage",
  E04 = "Building",
  E05 = "Locks; Keys; Window or door fittings; Safes",
  E06 = "Doors, windows, shutters, or roller blinds in general; Ladders",
  E21 = "Earth or rock drilling; Mining",
  E99 = "Subject matter not otherwise provided for in this section",
  
  F01 = "Machines or engines in general; Engine plants in general; Steam engines",
  F02 = "Combustion engines; Hot-gas or combustion-product engine plants",
  F03 = "Machines or engines for liquids; Wind, spring, or weight motors; Producing mechanical power",
  F04 = "Positive-displacement machines for liquids; Pumps for liquids or elastic fluids",
  F05 = "Indexing schemes relating to engines or pumps in various subclasses of classes F01-F04",
  F15 = "Fluid-pressure actuators; Hydraulics or pneumatics in general",
  F16 = "Engineering elements or units; General measures for producing and maintaining effective functioning",
  F17 = "Storing or distributing gases or liquids",
  F21 = "Lighting",
  F22 = "Steam generation",
  F23 = "Combustion apparatus; Combustion processes",
  F24 = "Heating; Ranges; Ventilating",
  F25 = "Refrigeration or cooling; Combined heating and refrigeration systems; Heat pump systems",
  F26 = "Drying",
  F27 = "Furnaces; Kilns; Ovens; Retorts",
  F28 = "Heat exchange in general",
  F41 = "Weapons",
  F42 = "Ammunition; Blasting",
  F99 = "Subject matter not otherwise provided for in this section",
  
  G01 = "Measuring; Testing",
  G02 = "Optics",
  G03 = "Photography; Cinematography; Analogous techniques using waves other than optical waves",
  G04 = "Horology",
  G05 = "Controlling; Regulating",
  G06 = "Computing; Calculating or counting",
  G07 = "Checking-devices",
  G08 = "Signalling",
  G09 = "Educating; Cryptography; Display; Advertising; Seals",
  G10 = "Musical instruments; Acoustics",
  G11 = "Information storage",
  G12 = "Instrument details",
  G16 = "Information and communication technology specially adapted for specific application fields",
  G21 = "Nuclear physics; Nuclear engineering",
  G99 = "Subject matter not otherwise provided for in this section",
  
  H01 = "Electric elements",
  H02 = "Generation, conversion, or distribution of electric power",
  H03 = "Electronic circuitry",
  H04 = "Electric communication technique",
  H05 = "Electric techniques not otherwise provided for",
  H99 = "Subject matter not otherwise provided for in this section",
  
  Y02 = "Technologies or applications for mitigation or adaptation against climate change",
  Y04 = "Information or communication technologies having an impact on other technology areas",
  Y10 = "Technical subjects covered by former USPC"
)



```



```{r}
ll=cpc_df %>% pull(heading) %>% unlist()

 paste(ll,",") %>% cat()

```


```{r}

#rm(sectionmap)
library(fst)
countrymap=read_fst("countrymap.fst")

sectionmap1=sectionmap1 %>% inner_join(countrymap %>% distinct(docdb_family_id)) %>% 
  inner_join(cpc_df) %>% 
  
sections=sectionmap1  %>% rename(technology=heading) %>% select(-section)





library(fst)
techmap <- read_fst("techmap.fst")
techs=techmap %>% distinct(technology)

if(!"Physics" %in% techs){
  techmap=techmap %>% bind_rows(sections)
  techmap=techmap %>% distinct()
  
  techmap=techmap %>%  inner_join(countrymap %>% distinct(docdb_family_id))
  #write_parquet(techmap,"techmap.parquet")
  write_fst(techmap,"techmap.fst",compress=100)
}




```



# Write things to dropbox

```{r}
# install.packages("scales")
library(scales)
scales::show_col(colors()[30:50])


```