---
title: "Prepare various bits of data"
output: html_notebook
---

```{r}

library(dplyr)

```



```{r}
library(dplyr)
if (Sys.info()["nodename"] == "PCACL-9RVSQ74") {
  datad="C:\\Users\\rmartin7\\OneDrive - WBG\\projects\\PRINZGlobal\\imperial_college_visualization\\01_data"
  localbig="C:\\Users\\rmartin7\\OneDrive - Imperial College London\\inglobe"
  ifcone="C:\\Users\\rmartin7\\OneDrive - WBG\\projects\\PRINZGlobal\\KEVCexplorer"
}

```


# cpc data

```{r}
cpcfile=paste0(localbig,"\\data\\cpcs.parquet")
if (!file.exists(cpcfile)) {
  library(bigrquery)
  library(DBI)
  
  # Set your project ID
  project_id <- "patbis"
  
  # Option 1: Direct table download
  # Specify dataset and table name
  dataset <- "fromPATSTAT2021"
  table <- "tls225_docdb_fam_cpc"
  
  # Download the entire table
  cpcs <- bq_table_download(
    bq_table(project_id, dataset, table)
  )
  
  
  cpcs=cpcs %>% select(docdb_family_id,cpc_class_symbol)
  cpcs=cpcs %>% arrange(docdb_family_id)
  library(arrow)
  write_parquet(cpcs,cpcfile)
}




```


  
```{r}

library(arrow)
cpcs=read_parquet(cpcfile)

cpcs=cpcs %>% arrange(docdb_family_id)


library(stringr)



cpcs=cpcs %>% gsub(" ", "", cpc_class_symbol)



library(data.table)
library(stringi)

setDT(cpcs)
cpcs[, cpc_class_symbol := stri_replace_all_fixed(cpc_class_symbol, " ", "")]


```


# Battery technology

## mapping file
```{r}


source("extrasectorshelper.r") # definitions of the battery sector

battery_df_expanded <- battery_df %>%
  separate_rows(CPC, sep = ";")%>%
  mutate(cpc_class_symbol = trimws(CPC))

setDT(battery_df_expanded)
battery_df_expanded[, cpc_class_symbol := stri_replace_all_fixed(cpc_class_symbol, " ", "")]


battery_df %>% 
  distinct(technology) %>% 
  pull(technology) %>% 
  paste0('"', ., '"') %>%
  paste(collapse = ", ") %>% cat()



batteryclasses=cpcs %>% inner_join(battery_df_expanded %>% select(technology,cpc_class_symbol)) 

all=batteryclasses %>% distinct(docdb_family_id) %>% mutate(technology="Any battery")
batteryclasses=batteryclasses %>% bind_rows(all)
batteryclasses=batteryclasses %>% select(docdb_family_id,technology)


```



```{r}
techmap <- read_parquet("techmap.parquet")
techs=techmap %>% distinct(technology)
if(!"Any battery" %in% techs){
  techmap=techmap %>% bind_rows(batteryclasses)
  
  techmap = techmap %>% mutate(technology=ifelse(technology=="Any battery","Any battery technology",technology))
  techmap = techmap %>% mutate(technology=ifelse(technology=="Any Green","Any Green technology",technology))
  write_parquet(techmap,"techmap.parquet")
}


```



