---
title: "Prepare various bits of data"
output: html_notebook
---


Prepares extra sectors....

```{r}

library(dplyr)

```



```{r}
library(dplyr)
if (Sys.info()["nodename"] == "PCACL-9RVSQ74") {
  datad="C:\\Users\\rmartin7\\OneDrive - WBG\\projects\\PRINZGlobal\\imperial_college_visualization\\01_data"
  localbig="C:\\Users\\rmartin7\\OneDrive - Imperial College London\\inglobe"
  ifcone="C:\\Users\\rmartin7\\OneDrive - WBG\\projects\\PRINZGlobal\\KEVCexplorer"
}




source("istraxfunctions.R")
dropbox_root <- get_dropbox_path()


```


# cpc data

```{r}
cpcfile=paste0(dropbox_root,"\\apps\\iseapp\\background_data\\cpcs.fst")
if (!file.exists(cpcfile)) {
  library(bigrquery)
  library(DBI)
  
  # Set your project ID
  project_id <- "patbis"
  
  # Option 1: Direct table download
  # Specify dataset and table name
  dataset <- "fromPATSTAT2021"
  table <- "tls225_docdb_fam_cpc"
  
  # Download the entire table
  cpcs <- bq_table_download(
    bq_table(project_id, dataset, table)
  )
  
  
  cpcs=cpcs %>% select(docdb_family_id,cpc_class_symbol)
  cpcs=cpcs %>% arrange(docdb_family_id)
  # library(fst2)
  write_fst(cpcs,cpcfile,compress=100)
}




```


  
```{r}

library(fst)
cpcs=read_fst(cpcfile)


#test=cpcs %>% summarize(n_distinct(docdb_family_id))

cpcs=cpcs %>% arrange(docdb_family_id)

head(cpcs)
library(stringr)

## get sections...
sectionmap1=cpcs %>% mutate(section=substr(cpc_class_symbol,1,1)) %>%
  select(section,docdb_family_id) %>% 
  distinct()

sectionmap1 %>% distinct(section) %>% nrow()
sectionmap1 %>% distinct(section) %>% pull(section)  %>% cat()


sectionmap2=cpcs %>% mutate(section=substr(cpc_class_symbol,1,3)) %>%
  select(section,docdb_family_id) %>% 
  distinct()

sectionmap2 %>% distinct(section) %>% nrow()
sectionmap2 %>% distinct(section) %>% pull(section)  %>% cat()



#cpcs=cpcs %>% gsub(" ", "", cpc_class_symbol)



library(data.table)
library(stringi)

setDT(cpcs)
cpcs[, cpc_class_symbol := stri_replace_all_fixed(cpc_class_symbol, " ", "")]

head(cpcs)
```





# Agriculture & Food Value Chains

```{r}
library(readxl)
library(data.table)
library(stringi)
tech_df <- read_excel("Agriculture_Food_CPC_Patents_2026-01-22.xlsx", sheet=1) %>%
  rename(CPC=`CPC Group/Subgroup`, technology=`Value Chain`) %>%
  filter(!is.na(technology), !is.na(CPC))


tech_df_expanded <- tech_df %>%
  separate_rows(CPC, sep = ";") %>%
  mutate(cpc_class_symbol = trimws(CPC))

setDT(tech_df_expanded)
tech_df_expanded[, cpc_class_symbol := stri_replace_all_fixed(cpc_class_symbol, " ", "")]


tech_df %>%
  distinct(technology) %>%
  pull(technology) %>%
  paste0('"', ., '"') %>%
  paste(collapse = ", ") %>% cat()



tech_classes=cpcs %>% inner_join(tech_df_expanded %>% select(technology,cpc_class_symbol))

all=tech_classes %>% distinct(docdb_family_id) %>% mutate(technology="Any Agriculture & Food technology")
tech_classes=tech_classes %>% bind_rows(all)
tech_classes=tech_classes %>% select(docdb_family_id,technology)



```



```{r}

library(fst)
techmapfile=paste0(dropbox_root,"\\apps\\iseapp\\techmap.fst")

techmap <- read_fst(techmapfile)
techs=techmap %>% distinct(technology)

#if(!"Input supply" %in% techs$technology){
  techmap=techmap %>% bind_rows(tech_classes)
  techmap=techmap %>% distinct()
  write_fst(techmap,techmapfile,compress=100)
#}



```

